### ISSUE TITLE
Change iframe code example to allow access to clipboard

### ISSUE THREAD

**Issue by bohwaz** [CollaboraOnline/collabora-online-sdk-examples#29]
Currently in Chrome, copy/paste doesn't work unless you add the specific allow attribute to the iframe tag, as documented here: https://sdk.collaboraonline.com/docs/advanced_integration.html#allow-the-clipboard-permission-query

This example should mention it.

**Comment by meven** [comment]
Indeed we would need to add ` allow="clipboard-read *; clipboard-write *"` to all our iframe declarations like:
https://github.com/CollaboraOnline/collabora-online-sdk-examples/blob/master/webapp/reactjs/client/src/App.tsx#L79C18-L79C117

And for the other examples.

**Comment by hfiguiere** [comment]
Thanks for reporting this.
